org.gradle.configuration-cache = true
org.gradle.parallel            = true
org.gradle.caching             = true

project.group                  = io.github.aj8gh
project.version                = 0.0.1-SNAPSHOT
project.main-class             = io.github.aj8gh.urlshortener.UrlShortenerAppKt
project.name                   = url-shortener
